language: node_js
node_js:
  - "8"

sudo: false

cache:
  - apt
  - packages
  - yarn

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
env:
  - CC=gcc-4.9
  - CXX=g++-4.9
